version: "3.8"

services:
  media-organizer:
    build: .
    container_name: media-organizer
    restart: unless-stopped
    environment:
      - TMDB_API_KEY=07204b56f116aa64c5b68ec20c12ae75
      - SCAN_INTERVAL=3600
      - DRY_RUN=false
      - LOG_LEVEL=INFO
    volumes:
      - /home/ubuntu/.config/rclone:/root/.config/rclone
      - ./data:/app/data
      - ./logs:/app/logs
